### ISSUE TITLE
Add an HTML file to start off the website

### ISSUE THREAD

**Issue by Diamafo** [EESTECXanthi/template-repo#6]
## Task Description

Work on the doctype and include some content for the website.

## Deadline

The task should be completed by the **01-01-2024**.

## Subtasks

The subtasks or steps that need to be completed to fulfil this issue are the following:

- [x] Add a Heading element.
- [x] Add a Paragraph element.
- [x] Change the browser window title.

## Needed Resources

- [Media files.]()
- [Brand Policy Paper.](https://drive.google.com/file/d/1hNf1ygFONIxE_-tMg_q2EHh8w0qrJ3f0/view)
- [Design Mockups.](https://drive.google.com/drive/folders/1BemSaKh5EzRqts6yInm4tm9U8FaQcyvY?usp=drive_link)
- **Fonts Used:** [Roboto Family](https://fonts.google.com/specimen/Roboto)
- **Colours Used:**
    - EESTEC Red: #E52A30
    - White: #FFFFFF
    - Black: #000000

**NOTE:** All the other useful links are in the ``Useful Information`` list.
